// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function supabaseAsCaller(ctx) {
  const token = ctx?.getToken?.();
  if (!token) throw new Error("Authentication required: sign in to modify catalog data.");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false },
    global: { headers: { Authorization: `Bearer ${token}` } }
  });
}

// src/lib/mcp/tools/list-catalogs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_catalogs_default = defineTool({
  name: "list_catalogs",
  title: "List catalogs",
  description: "List all catalogs with their id, name and product count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("catalogs").select("id, name, created_at, updated_at, products(count)").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const catalogs = (data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      productCount: c.products?.[0]?.count ?? 0,
      updatedAt: c.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(catalogs, null, 2) }],
      structuredContent: { catalogs }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_products_default = defineTool2({
  name: "list_products",
  title: "List products",
  description: "List products of a catalog in their manual display order.",
  inputSchema: {
    catalog_id: z.string().describe("Catalog id returned by list_catalogs."),
    include_page_breaks: z.boolean().optional().describe("Include page-break markers (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ catalog_id, include_page_breaks }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("products").select("id, name, description, price, image_url, position, is_page_break").eq("catalog_id", catalog_id).order("position", { ascending: true });
    if (!include_page_breaks) query = query.eq("is_page_break", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-product.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_product_default = defineTool3({
  name: "create_product",
  title: "Create product",
  description: "Add a product to a catalog. It is appended at the end of the catalog order.",
  inputSchema: {
    catalog_id: z2.string().describe("Catalog id to add the product to."),
    name: z2.string().describe("Product name."),
    price: z2.number().describe("Product price."),
    description: z2.string().optional().describe("Optional product description."),
    image_url: z2.string().optional().describe("Optional public image URL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ catalog_id, name, price, description, image_url }, ctx) => {
    const supabase = supabaseAsCaller(ctx);
    const { data: last } = await supabase.from("products").select("position").eq("catalog_id", catalog_id).order("position", { ascending: false }).limit(1);
    const position = (last?.[0]?.position ?? -1) + 1;
    const { data, error } = await supabase.from("products").insert({ catalog_id, name, price, description: description ?? null, image_url: image_url ?? null, position }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/update-product.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var update_product_default = defineTool4({
  name: "update_product",
  title: "Update product",
  description: "Update name, price, description or image of an existing product.",
  inputSchema: {
    id: z3.string().describe("Product id."),
    name: z3.string().optional(),
    price: z3.number().optional(),
    description: z3.string().optional(),
    image_url: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id, name, price, description, image_url }, ctx) => {
    const updates = {};
    if (name !== void 0) updates.name = name;
    if (price !== void 0) updates.price = price;
    if (description !== void 0) updates.description = description;
    if (image_url !== void 0) updates.image_url = image_url;
    if (Object.keys(updates).length === 0) {
      return { content: [{ type: "text", text: "No fields to update." }], isError: true };
    }
    const supabase = supabaseAsCaller(ctx);
    const { data, error } = await supabase.from("products").update(updates).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/delete-product.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var delete_product_default = defineTool5({
  name: "delete_product",
  title: "Delete product",
  description: "Permanently delete a product from its catalog.",
  inputSchema: { id: z4.string().describe("Product id to delete.") },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const supabase = supabaseAsCaller(ctx);
    const { error } = await supabase.from("products").delete().eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Deleted product ${id}` }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "my-joyful-portfolio",
  title: "My Joyful Portfolio",
  version: "0.1.0",
  instructions: "Tools for the product catalog app. Use `list_catalogs` to find a catalog id, `list_products` to read its products in display order, and `create_product` / `update_product` / `delete_product` to manage items. Prices are numbers in BRL. Callers must be signed in.",
  auth: auth.oauth.issuer({
    issuer: `${supabaseProjectUrl()}/auth/v1`,
    acceptedAudiences: "authenticated",
    resourceName: "My Joyful Portfolio"
  }),
  tools: [list_catalogs_default, list_products_default, create_product_default, update_product_default, delete_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
